doctrine_migrations:
    storage:
        table_storage:
            table_name: 'migration_versions'
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
    transactional: false
