doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
    transactional: false
    storage:
        table_storage:
            table_name: 'migration_versions'
    custom_template: '%kernel.project_dir%/migrations/MigrationTemplate.txt'
