fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: App\Entity\User
    from_email:
        address: '%env(MAILER_FROM)%'
        sender_name: "Kimai 2"
    registration:
        confirmation:
            enabled: false
    resetting:
        retry_ttl: 7200
        token_ttl: 86400
    service:
        mailer: App\Mail\UserMails
