framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: ~
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    cache:
        # The app cache caches to the filesystem by default. Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

    #available with Symfony 4.1
    #validation:
        # possible values: 'loose', 'strict', 'html5'
        #email_validation_mode: 'html5'

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
