monolog:
    channels: ["deprecation"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: notice
                handler: nested
                excluded_http_codes: [403, 404]
                channels: ["!deprecation"]
            nested:
                type: stream
                level: info
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                formatter: monolog.formatter.kimai
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!deprecation"]
# deactivated, because currently there are too many deprecations cause by gedmo and doctrine
#            deprecation:
#                type: stream
#                channels: ["deprecation"]
#                path: "%kernel.logs_dir%/deprecations.log"
#                formatter: monolog.formatter.deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!deprecation"]
                formatter: monolog.formatter.kimai
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!deprecation"]
            deprecation:
                type: stream
                channels: ["deprecation"]
                path: "%kernel.logs_dir%/deprecations.log"
                formatter: monolog.formatter.deprecation

when@test:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: ["!event"]
                formatter: monolog.formatter.kimai
