twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/vertical.html.twig'
    paths:
        '%kernel.project_dir%/templates/bundles/TablerBundle': theme
        '%kernel.project_dir%/vendor/kevinpapst/tabler-bundle/templates': theme
