twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/vertical.html.twig'
    paths:
        '%kernel.project_dir%/templates/bundles/TablerBundle': theme
        '%kernel.project_dir%/vendor/kevinpapst/tabler-bundle/templates': theme
    globals:
        app: '@App\Twig\AppVariable'

when@test:
    twig:
        strict_variables: true
