language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  mariadb: '10.2'

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

before_install:
#  - phpenv config-rm xdebug.ini
  - composer self-update
  - php -i

install:
  - composer install

script:
  - php -r "echo date(DATE_RFC850);"
  - composer ci
  - cp tests/.env.dist.sqlite .env
  - bin/console doctrine:database:create -n
  - bin/console doctrine:migrations:migrate -n
  - bin/console doctrine:migrations:migrate first -n
  - cp tests/.env.dist.mysql .env
  - bin/console doctrine:database:create -n
  - bin/console doctrine:migrations:migrate -n
  - bin/console doctrine:migrations:migrate first -n
  - bash <(curl -s https://codecov.io/bash)