controllers:
    resource: '../../src/Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

app.api:
    resource: '../src/API/'
    type: rest
    prefix: /api
