App\Entity\Activity:
    exclusion_policy: All
    custom_accessor_order: [id, name, comment, visible, project_id, fixedRate, hourlyRate]
    properties:
        id:
            include: true
        name:
            include: true
        comment:
            include: true
        visible:
            include: true
        fixedRate:
            include: true
        hourlyRate:
            include: true
    virtual_properties:
        getProjectId:
            name: project_id
            serialized_name: project_id
            exp: "object.getProject() === null ? null : object.getProject().getId()"
            type: integer
