App\Entity\Team:
    exclusion_policy: All
    custom_accessor_order: [id, name, teamlead, users, customers, projects]
    properties:
        id:
            include: true
        name:
            include: true
        teamlead:
            include: true
            groups: [Team_Entity]
        users:
            include: true
            groups: [Team_Entity]
        customers:
            include: true
            groups: [Team_Entity]
        projects:
            include: true
            groups: [Team_Entity]
