doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        result_cache_driver:
            type: service
            id: doctrine.result_cache_provider

services:
    doctrine.result_cache_provider:
        factory: [ 'Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap' ]
        class: Doctrine\Common\Cache\Psr6\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        factory: [ 'Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap' ]
        class: Doctrine\Common\Cache\Psr6\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
