parameters:
    locale: en
    kimai_locales: ['ar', 'cs', 'de', 'de_CH', 'da', 'en', 'eo', 'es', 'eu', 'fr', 'he', 'hu', 'it', 'ja', 'ko', 'nl', 'pl', 'pt_BR', 'ro', 'ru', 'sk', 'sv', 'tr', 'vi', 'zh_CN']

services:
    _defaults:
        public: true

    App\Configuration\SystemConfiguration:
        arguments: ['@App\Configuration\ConfigurationService', "%kimai.config%"]

    # required for the importer command test
    App\Repository\UserRepository:
        class:     Doctrine\ORM\EntityRepository
        factory:   ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['App\Entity\User']

    # required for the importer command test
    App\Importer\ImporterService:
        public: true
        arguments: ['@App\Customer\CustomerService', '@App\Project\ProjectService']

    App\User\UserService:
        public: true
        arguments: ['@App\Repository\UserRepository', '@event_dispatcher', '@validator', '@App\Configuration\SystemConfiguration', '@security.user_password_hasher']
