parameters:
    locale: en
    kimai_locales: ['ar', 'cs', 'de', 'de_CH', 'da', 'en', 'eo', 'es', 'eu', 'fr', 'he', 'hu', 'it', 'ja', 'ko', 'nl', 'pl', 'pt_BR', 'ro', 'ru', 'sk', 'sv', 'tr', 'vi', 'zh_CN']

services:
    _defaults:
        public: true

    App\Configuration\SystemConfiguration:
        arguments: ['@App\Configuration\ConfigurationService', "%kimai.config%"]

    App\User\UserService:
        public: true
        arguments: ['@App\Repository\UserRepository', '@event_dispatcher', '@validator', '@App\Configuration\SystemConfiguration', '@security.user_password_hasher']
