doctrine:
     orm:
         dql:
             datetime_functions:
                 date: DoctrineExtensions\Query\Sqlite\Date
                 date_format: DoctrineExtensions\Query\Sqlite\DateFormat
                 #dateadd: DoctrineExtensions\Query\Sqlite\DateAdd
                 #datediff: DoctrineExtensions\Query\Sqlite\DateDiff
                 day: DoctrineExtensions\Query\Sqlite\Day
                 dayname: DoctrineExtensions\Query\Sqlite\DayName
                 hour: DoctrineExtensions\Query\Sqlite\Hour
                 julianday: DoctrineExtensions\Query\Sqlite\JulianDay
                 minute: DoctrineExtensions\Query\Sqlite\Minute
                 #month: DoctrineExtensions\Query\Sqlite\Month
                 #monthname: DoctrineExtensions\Query\Sqlite\MonthName
                 second: DoctrineExtensions\Query\Sqlite\Second
                 month:  DoctrineExtensions\Query\Sqlite\Month
                 strftime:  DoctrineExtensions\Query\Sqlite\StrfTime
                 #strtodate: DoctrineExtensions\Query\Sqlite\StrToDate
                 #time: DoctrineExtensions\Query\Sqlite\Time
                 #timestampadd: DoctrineExtensions\Query\Sqlite\TimestampAdd
                 #timestampdiff: DoctrineExtensions\Query\Sqlite\TimestampDiff
                 week: DoctrineExtensions\Query\Sqlite\Week
                 weekday: DoctrineExtensions\Query\Sqlite\WeekDay
                 year: DoctrineExtensions\Query\Sqlite\Year


             string_functions:
#                 binary: DoctrineExtensions\Query\Sqlite\Binary
#                 char_length: DoctrineExtensions\Query\Sqlite\CharLength
                 concat_ws: DoctrineExtensions\Query\Sqlite\ConcatWs
#                 countif: DoctrineExtensions\Query\Sqlite\CountIf
#                 crc32: DoctrineExtensions\Query\Sqlite\Crc32
#                 degrees: DoctrineExtensions\Query\Sqlite\Degrees
#                 field: DoctrineExtensions\Query\Sqlite\Field
#                 find_in_set: DoctrineExtensions\Query\Sqlite\FindInSet
#                 group_concat: DoctrineExtensions\Query\Sqlite\GroupConcat
                 greatest: DoctrineExtensions\Query\Sqlite\Greatest
                 ifelse: DoctrineExtensions\Query\Sqlite\IfElse
                 ifnull: DoctrineExtensions\Query\Sqlite\IfNull
                 least: DoctrineExtensions\Query\Sqlite\Least
#                 match: DoctrineExtensions\Query\Sqlite\MatchAgainst
#                 md5: DoctrineExtensions\Query\Sqlite\Md5
#                 nullif: DoctrineExtensions\Query\Sqlite\NullIf
#                 radians: DoctrineExtensions\Query\Sqlite\Radians
                 random: DoctrineExtensions\Query\Sqlite\Random
#                 regexp: DoctrineExtensions\Query\Sqlite\Regexp
                 replace: DoctrineExtensions\Query\Sqlite\Replace
#                 sha1: DoctrineExtensions\Query\Sqlite\Sha1
#                 sha2: DoctrineExtensions\Query\Sqlite\Sha2
#                 soundex: DoctrineExtensions\Query\Sqlite\Soundex
#                 uuid_short: DoctrineExtensions\Query\Sqlite\UuidShort

             numeric_functions:
                 round: DoctrineExtensions\Query\Sqlite\Round
