name: 'Lock Threads'

on:
    schedule:
        - cron: '17 1 * * *'
    workflow_dispatch:

permissions:
    issues: write
    pull-requests: write

concurrency:
    group: lock-threads

jobs:
    action:
        runs-on: ubuntu-latest
        steps:
            - uses: dessant/lock-threads@v5
              with:
                  github-token: ${{ github.token }}
                  issue-inactive-days: '90'
                  exclude-issue-created-before: ''
                  exclude-issue-created-after: ''
                  exclude-issue-created-between: ''
                  exclude-issue-closed-before: ''
                  exclude-issue-closed-after: ''
                  exclude-issue-closed-between: ''
                  include-any-issue-labels: ''
                  include-all-issue-labels: ''
                  exclude-any-issue-labels: ''
                  add-issue-labels: ''
                  remove-issue-labels: ''
                  issue-comment: >
                    This thread has been automatically locked since there has not been any recent activity after it was closed. 
                    Please share your experience with the community and [leave a testimonial](https://love.kimai.org/) to support Kimai.
                  issue-lock-reason: 'resolved'
                  pr-inactive-days: '180'
                  exclude-pr-created-before: ''
                  exclude-pr-created-after: ''
                  exclude-pr-created-between: ''
                  exclude-pr-closed-before: ''
                  exclude-pr-closed-after: ''
                  exclude-pr-closed-between: ''
                  include-any-pr-labels: ''
                  include-all-pr-labels: ''
                  exclude-any-pr-labels: ''
                  add-pr-labels: ''
                  remove-pr-labels: ''
                  pr-comment: ''
                  pr-lock-reason: ''
                  process-only: ''
                  log-output: true
